variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - check
  - build

before_script:
  - node --version
  - npm install

prettier:
  stage: check
  image: node:12
  script:
    - npm run lint

jest:
  stage: check
  image: node:12
  script:
    - npm run test

nix-dry:
  stage: check
  script:
    - nix-shell ./shell.nix
    - nix-build -v -v --dry-run ./nix/default.nix -A library

npm-build:
  stage: build
  image: node:12
  script:
    - npm run build:library
    - npm run build:documentation

nix-build:
  stage: build
  script:
    - nix-shell ./shell.nix
    - nix-build ./nix/default.nix -A library -o result-0

