variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - check
  - build

image: registry.gitlab.com/matrixai/engineering/maintenance/gitlab-runner

lint:
  stage: check
  script:
    - nix-shell --packages nodejs --run "npm install"
    - nix-shell --packages nodejs --run "npm run lint"

test:
  stage: check
  script:
    - nix-shell --packages nodejs --run "npm install"
    - nix-shell --packages nodejs --run "npm run test"

nix-dry:
  stage: check
  script:
    - nix-build -v -v --dry-run ./release.nix --attr application
    - nix-build -v -v --dry-run ./release.nix --attr docker

nix:
  stage: build
  script:
    - >
      nix-build ./release.nix
      --attr application
      --attr docker
  only:
    - master
